# ============================================
# GitHub Actions Workflow File
# This workflow builds and packages the Eclipse Paho MQTT C project for macOS
# Triggered manually using GitHub UI via "workflow_dispatch"
# ============================================

name: "Upload release artifact for MacOS"  # The display name of the workflow
on: [workflow_dispatch]  # Trigger this workflow manually from the GitHub Actions tab

jobs:
  build:
    runs-on: macos-latest  # Use the latest available macOS runner in GitHub-hosted environment
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew update
          brew install doxygen
      - name: Build
        run: |
          rm -rf build.paho
          mkdir build.paho
          cd build.paho
          echo "pwd $PWD"
          cmake -DPAHO_BUILD_STATIC=FALSE -DPAHO_BUILD_SHARED=TRUE -DCMAKE_BUILD_TYPE=Debug -DPAHO_WITH_SSL=TRUE -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=TRUE -DPAHO_HIGH_PERFORMANCE=TRUE ..
          cmake --build .
      - name: package
        run: |
          cd build.paho
          cpack --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Eclipse-Paho-MQTT-C-1.3.14-Darwin.tar.gz  # Artifact name shown in GitHub
          path: /Users/runner/work/paho.mqtt.c/paho.mqtt.c/build.paho/Eclipse-Paho-MQTT-C-1.3.14-Darwin.tar.gz  # Path to the packaged file
